export const GET_DATA_BEGIN = "GET_DATA_BEGIN";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";
export const GET_FEATURED_DATA_BEGIN = "GET_FEATURED_DATA_BEGIN";
export const GET_FEATURED_DATA_SUCCESS = "GET_FEATURED_DATA_SUCCESS";
export const GET_FEATURED_DATA_FAILURE = "GET_FEATURED_DATA_FAILURE";
